2017-07-09 18:41:06 ERROR (MainThread) [homeassistant.config] Invalid config for [homeassistant]: expected dict for dictionary value @ data['customize']['group.dining_room']. Got None
expected dict for dictionary value @ data['customize']['group.living_room']. Got None
expected dict for dictionary value @ data['customize']['group.upstairs_hallway']. Got None. (See /home/homeassistant/.homeassistant/configuration.yaml, line 3). 
